NOME_PROTOCOLO=mahjong_protocolo

all:
#	g++ -std=c++11 Serial.cpp Enquadramento.cpp ARQ.cpp Protocolo.cpp main.cpp -o exec_protocolo
#	g++ -std=c++11 *.cpp -o exec_protocolo
	g++ -std=c++11 -c *.cpp
	g++ -o $(NOME_PROTOCOLO) *.o
clear:
	rm $(NOME_PROTOCOLO) *.o
